### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by ScottHuangZL** [evilz/fable-ant-design#5]
C:\Users\scott_huang\fable-antd\src> **dotnet fable yarn-start**
Fable (1.3.3) daemon started on port 61225
CWD: C:\Users\scott_huang\fable-antd
cmd /C yarn run start
yarn run v1.6.0
warning ..\package.json: No license field
$ webpack-dev-server
Bundling for development...
Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from C:\Users\scott_huang\fable-antd\public
Hash: 0600ec52ae8a200a85be
Version: webpack 3.12.0
Time: 696ms
        Asset    Size  Chunks                    Chunk Names
    bundle.js  355 kB       0  [emitted]  [big]  main
bundle.js.map  417 kB       0  [emitted]         main
[./node_modules/ansi-html/index.js] ./node_modules/ansi-html/index.js 4.26 kB {0} [built]
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
[./node_modules/querystring-es3/index.js] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
   [0] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/fable_antd.fsproj 52 bytes {0} [built]
[./node_modules/sockjs-client/dist/sockjs.js] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} [built]
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {0} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {0} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.04 kB {0} [built]
    + 12 hidden modules

**ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/fable_antd.fsproj
Module not found: Error: Can't resolve 'C:\Users\scott_huang\fable-antd\src\fable_antd.fsproj' in 'C:\Users\scott_huang\fable-antd'
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/fable_antd.fsproj
webpack: Failed to compile.**

**Comment by ScottHuangZL** [comment]
It will work in case I create folder as fable_a_new_folder instead of fable-a-new-folder.

However, can you fix the limitation? thanks.

**Comment by evilz** [comment]
Not sure it's may be a problem in fable or webpack but not in this project.
